INSERT INTO [SalesProject].[dbo].[DIMProduct] (
    [ProductKey],
    [ProductAlternateKey],
    [ProductSubcategoryKey],
    [WeightUnitMeasureCode],
    [SizeUnitMeasureCode],
    [EnglishProductName],
    [StandardCost],
    [FinishedGoodsFlag],
    [Color],
    [SafetyStockLevel],
    [ReorderPoint],
    [ListPrice],
    [Size],
    [SizeRange],
    [Weight],
    [DaysToManufacture],
    [ProductLine],
    [DealerPrice],
    [Class],
    [Style],
    [ModelName],
    [LargePhoto],
    [EnglishDescription],
    [StartDate],
    [EndDate],
    [Status],
    [LastUpdate] 
)
SELECT 
    CAST([ProductKey] AS INT), 
    [ProductAlternateKey],
    CAST([ProductSubcategoryKey] AS NVARCHAR(500)), 
    CAST([WeightUnitMeasureCode] AS NCHAR(255)),
    CAST([SizeUnitMeasureCode] AS NCHAR(255)),
    CAST([EnglishProductName] AS NVARCHAR(500)),
    CAST([StandardCost] AS MONEY), 
    CAST([FinishedGoodsFlag] AS BIT), 
    [Color],
    CAST([SafetyStockLevel] AS SMALLINT),
    CAST([ReorderPoint] AS SMALLINT), 
    CAST([ListPrice] AS MONEY), 
    [Size],
    [SizeRange],
    CAST([Weight] AS FLOAT), 
    CAST([DaysToManufacture] AS INT), 
    CAST([ProductLine] AS NCHAR(255)), 
    CAST([DealerPrice] AS MONEY), 
    CAST([Class] AS NCHAR(255)),
    CAST([Style] AS NCHAR(255)),
    CAST([ModelName] AS NVARCHAR(500)), 
    CONVERT(VARBINARY(MAX), [LargePhoto]), 
    CAST([EnglishDescription] AS NVARCHAR(400)), 
    [StartDate], 
    TRY_CAST([EndDate] AS DATETIME),
    [Status],
    GETDATE() 
FROM [SalesProject].[dbo].[STGProduct];


 