name: Deploy to Azure SQL

on:
  push:
    branches:
      - prod
    paths:
      - 'SQLProd/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQLCMD tools
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Deploy SQL files to Azure SQL Database
        run: |
          for file in SQLProd/*.sql; do
            echo "Deploying $file..."
            /opt/mssql-tools/bin/sqlcmd \
              -S ${{ secrets.AZURE_SQL_SERVER }} \
              -d ${{ secrets.AZURE_SQL_DB_NAME }} \
              -U ${{ secrets.AZURE_SQL_USERNAME }} \
              -P ${{ secrets.AZURE_SQL_PASSWORD }} \
              -i "$file"
          done
