name: CD - Promote SQLQA to SQLProd

on:
  workflow_run:
    workflows: ["CI - Lint SQL"]
    types:
      - completed

jobs:
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch with PAT (read-only)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          ref: main
          path: main_branch

      - name: Checkout prod branch with PAT (write)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          ref: prod
          path: prod_branch

      - name: Promote SQL files from main's SQLQA to prod's SQLProd
        run: |
          mkdir -p prod_branch/SQLProd
          cp -v main_branch/SQLQA/*.sql prod_branch/SQLProd/

      - name: Commit and push to prod branch
        working-directory: prod_branch
        run: |
          git config user.name "Hashwin Bot"
          git config user.email "hashwin@users.noreply.github.com"
          git add SQLProd/
          git commit -m "CD: Promoted SQL files from main/SQLQA to prod/SQLProd" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Hashwinn/Sales-Dashboard.git HEAD:prod
