name: CD - Promote SQLQA to SQLProd

on:
  push:
    paths:
      - 'SQLQA/**'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files from SQLQA to SQLProd
        run: |
          mkdir -p SQLProd
          cp -v SQLQA/*.sql SQLProd/

      - name: Commit and push changes
        run: |
          git config user.name "CD_TOKEN"
          git config user.email "hashwin@users.noreply.github.com"
          git add SQLProd/
          git commit -m "CD: Promoted SQL files from SQLQA to SQLProd"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Hashwinn/Sales-Dashboard.git HEAD:main
