name: CD - Promote SQLQA to SQLProd

on:
  push:
    paths:
      - 'SQLQA/**'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Promote tested SQL files to SQLProd
        run: |
          mkdir -p SQLProd
          cp -v SQLQA/*.sql SQLProd/

      - name: Commit and push promoted files
        run: |
          git config user.name "Hashwin Bot"
          git config user.email "hashwin@users.noreply.github.com"
          git add SQLProd/
          git commit -m "CD: Promoted SQL files from SQLQA to SQLProd" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Hashwinn/Sales-Dashboard.git HEAD:main
