name: SQLFluff CD - Promote Tested Files

on:
  push:
    paths:
      - 'SQLQA/**'
    branches:
      - main

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy files to SQLProd
        run: |
          mkdir -p SQLProd
          cp -r SQLQA/*.sql SQLProd/

      - name: Commit changes
        run: |
          git add SQLProd/
          git commit -m "CD: Promoted SQL files from SQLQA to SQLProd" || echo "No changes to commit"

      - name: Push to main branch
        env:
          TOKEN: ${{ secrets.CD_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Hashwinn/Sales-Dashboard.git
          git push origin main
